### ISSUE TITLE
bug: `maximum callstack exceeded` errors due to `msgpackr` 

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia-ide#265]
#### Bug Description:

There is an issue following https://github.com/eclipse-theia/theia-blueprint/commit/6ddc6e3a0316e52cefd9e9ca29a9f76d8d57245c where the upgrade to `msgpackr` is causing `maximum callstack exceeded` errors due to https://github.com/eclipse-theia/theia/issues/12499. We added a `resolution` note in the main repo as a workaround until fixed:

- https://github.com/eclipse-theia/theia/blob/master/doc/Migration.md#general

```
rpc-message-encoder.ts:151 Uncaught (in promise) Error: Error during encoding: 'Maximum call stack size exceeded'
    at t.MsgPackMessageEncoder.encode (rpc-message-encoder.ts:151:23)
    at t.MsgPackMessageEncoder.request (rpc-message-encoder.ts:137:14)
    at l.sendRequest (rpc-protocol.ts:161:22)
    at proxy-handler.ts:74:45
```

https://github.com/eclipse-theia/theia-blueprint/blob/5850adb9220e3cea711ebcf4ef89852c7720778e/yarn.lock#L9567-L9568

#### Steps to Reproduce:

1. start the application
2. notice the `maximum callstack exceeded` logs

#### Additional Info

- https://github.com/eclipse-theia/theia/issues/12574

**Comment by badrihcl** [comment]
The mentioned workaround works and exception isn't thrown . But we still have the connection issue as mentioned in https://github.com/eclipse-theia/theia/issues/12574.

The issue occurs only with Theia Blueprint 1.37 and not with Theia Blueprint 1.36 for the same vscode extension.

![image](https://github.com/eclipse-theia/theia-blueprint/assets/127408770/4272b6eb-c54f-4e24-afdc-342dae7822ea)

Should I raise a separate defect for this ?

**Comment by vince-fugnitto** [comment]
@badrihcl I don't have an environment to test, if you can debug as to why it happens first that would be helpful.

**Comment by marcdumais-work** [comment]
@badrihcl Can you try with Blueprint 1.38.0, that we recently made available? It pins `msgpackr` to an earlier version, known to work.

![image](https://github.com/eclipse-theia/theia-blueprint/assets/25749063/ea057a34-d2ea-4166-ad29-9865f30c4368)

Also, it seems that [`msgpackr` has a new version out](https://github.com/eclipse-theia/theia/issues/12499#issuecomment-1579956129) that contains a fix: `1.9.5`. Let us know if you still have the issue with Blueprint 1.38.0, and maybe we can upgrade its `msgpackr`.
