### ISSUE TITLE
Appimage wont start at all (1.51)(Wayland)

### ISSUE THREAD

**Issue by squalou** [eclipse-theia/theia-ide#377]
### Bug Description:

Downloaded latest Appimage, chmod +x, try to run it.

First I got a segmentation fault, tried again and since then  I get  

```
Error: node-loader:
Error: /tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/native/pty.node: cannot open shared object file: No such file or directory
    at 24632 (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/268.js:2:599)
```

sometimes the seg fault is back

### Steps to Reproduce:

1. Download latet AppImage (at the moment : 1.51)
2. chmod +x TheiaIDE.AppImage
3. ./TheiaIDE.AppImage

```
Error: node-loader:
Error: /tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/native/pty.node: cannot open shared object file: No such file or directory
    at 24632 (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/268.js:2:599)
    at i (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/main.js:1:14494)
    at 85969 (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/268.js:2:1392011)
    at i (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/main.js:1:14494)
    at 87047 (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/268.js:2:1387699)
    at i (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/main.js:1:14494)
    at 3979 (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/268.js:2:410632)
    at i (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/main.js:1:14494)
    at 47552 (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/268.js:2:402568)
    at i (/tmp/.mount_TheiaInkhtIA/resources/app/lib/backend/main.js:1:14494)


```

### Additional Information

- Operating System: PopOS 22.04
- Theia Version: 1.51
- Using Wayland

### Workaround

see below to use x11 instead of wayland

**Comment by squalou** [comment]
OK probably my bad : I'm using wayland.

`./TheiaIDE.AppImage --ozone-platform=x11`

and it works

**Comment by JonasHelming** [comment]
@squalou Is this issue then closed for you or do you want to adapt the description?

**Comment by squalou** [comment]
> @squalou Is this issue then closed for you or do you want to adapt the description?

Well I don't know if this is to be considered an issue, or juste a missing documentation somewhere, 
I'll just adapt the description for now to help maybe other people find it,  but as far as I'm concerned you also could close the issue due to the workaround.

**Comment by maehne** [comment]
From my point of view, this is clearly a Wayland-related issue, which should be kept open until the workaround `--ozone-platform=x11` is not necessary.

**Comment by 0rzech** [comment]
Would `--ozone-platform-hint=wayland --enable-features=WaylandWindowDecorations` help you with Wayland use?

This is how I've been running Electron apps (including Theia) on my machine for a long time and they're fine.

I know of at least one case where it didn't help: https://github.com/Dygmalab/Bazecor/issues/683 , but it seems to be a different problem.

**Comment by tvannoy** [comment]
I just download the latest theia-ide appimage and ran into the same issue reported by OP. theia segfaults when being run for the first time without `--ozone-platform=x11`

I've included a workaround summary that lets Theia run wayland-native at the bottom. Below are some thoughts and debugging details.

# Debugging details

Running with `--ozone-platform=x11` lets theia run just fine. However, it uses x11-wayland, which doesn't support fractional scaling, so theia looks terrible on my laptop under x11-wayland.

I was able to run theia with `--ozone-platform=wayland` and it correctly uses wayland and fractional scaling works, so theia does indeed work natively on wayland. However, I tried running the appimage for the first time (immediately after downloading) using `--ozone-platform=wayland` and it segfaulted, so it appears that theia needs to be run under x11-wayland first, then it will work wayland-native after that.

Electron apps generally don't use wayland by default yet, so we have to run electron apps with `--ozone-platform=wayland` or `--ozone-platform-hint=wayland` (`--ozone-platform-hint=auto` also works sometimes). There's also an [ELECTRON_OZONE_PLATFORM_HINT environment variable](https://www.electronjs.org/docs/latest/api/environment-variables#electron_ozone_platform_hint-linux) that can be set.

I have `ELECTRON_OZONE_PLATFORM_HINT` set to auto. The appimage uses wayland without any arguments for me, i.e., `./TheiaIDE.AppImage` uses wayland. So indeed, `--ozone-platform=x11` is needed on first launch, but after that all the ways to force electron to use wayland appear to be working.

If someone else wants to verify that using `--ozone-platform=x11` is needed upon first launch, that would be great.

I don't think needing `--ozone-platform=x11` on first launch is an electron issue, but it might be. It could be a Theia issue or an electron issue. I did not need to use `--ozone-platform=x11` the first time I launched VS Codium, which makes me think this is a Theia issue. However, I haven't verified that Codium and Theia are using the same electron version.

---

# Workaround summary

To get Theia to use wayland:
1. Run the appimage with `--ozone-platform=x11` the first time you run it: `./TheiaIDE.AppImage --ozone-platform=x11`
2. Run Theia with `--ozone-platform=wayland`, `--ozone-platform-hint=wayland`, `--ozone-platform-hint=auto`, or setting the `ELECTRON_OZONE_PLATFORM_HINT` environment variable to auto or wayland.

**Comment by tsmaeder** [comment]
I just did the following on Ubuntu: 24.10

1. `echo $XDG_SESSION_TYPE` gives 'wayland'
2. Downloaded the latest app image (1.58.100)
3. chmod and run the app image
4. The IDE starts without trouble.

@tvannoy what am I missing?

**Comment by tvannoy** [comment]
Everything seems to be working fine for me now, too. I tried with the latest AppImage as well as a few other versions including 1.51 (which the issue started with). They all launched just fine for me under Wayland. I removed the `.theia` and `.config/Theia IDE` folders to try starting fresh each time, though maybe there was some leftover config somewhere else.

I am using the Cinnamon DE on Debian right now. Before I was using hyprland on Debian, which is broken right now so I can't test.

@tsmaeder I think we can close this issue. Everything seems to be working perfectly, at least on major distros and DEs.
